spring:
  datasource:
#    url: jdbc:mysql://47.94.238.122/youcai?useSSL=false
    url: jdbc:mysql:///youcai?useSSL=false
    password: qing1016..
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  resources:
    static-locations: file:${img.location}
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /manage
security:
  basic:
    enabled: false
img:
#  location: F:\temp\youcai\image
  location: /Users/macos/tmp/youcai/image
