spring:
  datasource:
#    url: jdbc:mysql://47.94.238.122/youcai?useSSL=false
    url: jdbc:mysql:///youcai?useSSL=false
#    url: jdbc:mysql://rm-2ze897dhq95z8g5603o.mysql.rds.aliyuncs.com:3306/youcai?useSSL=false
    password: qing1016..
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  resources:
    static-locations: file:${img.location}, classpath:/static/
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  context-path: /manage
security:
  basic:
    enabled: false
img:
  location: /youcai/back/image
#  location: /Users/macos/tmp/youcai/image
#  location: D:\Developers\files\youcai