spring:
  datasource:
    url: jdbc:mysql:///youcai?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    password: qing1016..
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  resources:
    static-locations: file:${img.location}, classpath:/static/
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  context-path: /manage
security:
  basic:
    enabled: false
img:
  location: /youcai/back/image